export type Service = {
  slug: string;
  title: string;
  hero: string;
  intro: string;
  whatWeTest: string[];
  approach: { phase: string; title: string; desc: string }[];
  deliverables: string[];
  whyTLN: string[];
  bestFor: string[];
};

export const services: Record<string, Service> = {
  external: {
    slug: "external",
    title: "External Penetration Testing",
    hero: "We attack your perimeter the way attackers do.",
    intro: "Your internet-facing assets are an attacker's first stop. We perform black-box reconnaissance and exploitation against your perimeter — the same TTPs real adversaries use, with none of the consequences.",
    whatWeTest: [
      "Public IP ranges, exposed services, perimeter firewalls",
      "Web servers, mail servers, VPNs, remote-access portals",
      "Subdomain takeover, DNS misconfigurations, certificate exposure",
      "Authentication portals (SSO, OAuth, federation)",
      "Cloud-edge services (S3, blob storage, public APIs)",
      "Leaked credentials + breach-data correlation",
    ],
    approach: [
      { phase: "01", title: "Reconnaissance", desc: "Passive OSINT + active scanning. We map your full external footprint before touching it." },
      { phase: "02", title: "Vulnerability Discovery", desc: "Combine automated scanning with manual analysis to surface real exploitable issues — not noise." },
      { phase: "03", title: "Exploitation & Validation", desc: "We prove findings with safe PoCs. No theoretical risk — actual demonstrated impact." },
      { phase: "04", title: "Reporting & Remediation", desc: "Executive + technical reports with the QSurface provenance chain. Retests included." },
    ],
    deliverables: [
      "Executive report (business-language risk summary)",
      "Technical findings with reproducible PoCs + severity",
      "QSurface provenance chain (cryptographically-signed engagement log)",
      "Remediation guidance with priority order",
      "Free retest of remediated findings within 90 days",
    ],
    whyTLN: [
      "AI-augmented coverage — we test more in less time",
      "Cryptographic audit chain your auditors will love",
      "Born in esports — we know how attackers actually move",
      "Charity-tied: every engagement supports VGP (501c3)",
    ],
    bestFor: ["Public-facing SaaS companies", "Regulated industries (finance, healthcare)", "Pre-Series A/B for security due diligence", "Annual compliance requirements (SOC 2, ISO 27001)"],
  },
  internal: {
    slug: "internal",
    title: "Internal Penetration Testing",
    hero: "Assume breach. Then see how far an insider can move.",
    intro: "Real attackers eventually get inside — through phishing, supply chain, or a single compromised credential. Internal pen testing simulates that foothold and measures how much damage is possible from there.",
    whatWeTest: [
      "Active Directory / identity infrastructure",
      "Internal network segmentation + lateral movement paths",
      "Privilege escalation opportunities (local + domain)",
      "Internal services, file shares, databases",
      "Endpoint detection bypass (EDR/AV evasion)",
      "Credential harvesting + reuse patterns",
    ],
    approach: [
      { phase: "01", title: "Foothold Setup", desc: "We start with the access level you specify — VPN credential, phishing-simulated endpoint, or direct network drop." },
      { phase: "02", title: "Internal Reconnaissance", desc: "Map your internal topology, identity infrastructure, and high-value assets the way an attacker would." },
      { phase: "03", title: "Lateral Movement & Privilege Escalation", desc: "Demonstrate the actual blast radius of the assumed compromise." },
      { phase: "04", title: "Reporting & Remediation", desc: "Detailed attack-path narrative + QSurface chain + prioritized remediation plan." },
    ],
    deliverables: [
      "Attack-path narrative (how we got from A to crown jewels)",
      "Technical findings with EDR/SIEM detection gaps noted",
      "QSurface provenance chain",
      "Identity + segmentation hardening recommendations",
      "Free retest within 90 days",
    ],
    whyTLN: [
      "We chain identity + network + endpoint findings into a single attack story",
      "Your blue team gets actionable detection-engineering input",
      "AI-augmented coverage of large internal estates",
      "QSurface chain proves exactly what we touched",
    ],
    bestFor: ["Mid-large enterprises with on-prem AD", "Companies post-incident hardening", "Mature security programs validating SOC capabilities", "Regulated industries needing assume-breach evidence"],
  },
  webapp: {
    slug: "webapp",
    title: "Web Application Security Testing",
    hero: "OWASP-aligned. Business-logic-savvy. Manual where it counts.",
    intro: "Modern web apps are complex — auth flows, multi-tenant isolation, business-logic guardrails, third-party integrations. Automated scanners miss the most expensive bugs. We don't.",
    whatWeTest: [
      "Authentication, authorization, session management",
      "Injection (SQL, NoSQL, LDAP, command, template)",
      "Business-logic flaws (price tampering, workflow bypass, IDOR)",
      "Multi-tenant isolation + access controls",
      "Third-party integrations (OAuth, SSO, payment gateways)",
      "Front-end security (XSS, CSRF, clickjacking, postMessage)",
      "API security (REST, GraphQL, gRPC)",
    ],
    approach: [
      { phase: "01", title: "Application Mapping", desc: "We learn your app's logic the way a power-user would — before testing for abuse." },
      { phase: "02", title: "Authenticated Testing", desc: "Multi-role testing across user tiers. Cross-tenant + privilege-escalation focus." },
      { phase: "03", title: "Business-Logic Exploitation", desc: "Where automated tools end, ours begin. Workflow bypass, race conditions, value tampering." },
      { phase: "04", title: "Reporting & Remediation", desc: "Reproducible PoCs, severity per OWASP + CVSS, QSurface chain, retests." },
    ],
    deliverables: [
      "Detailed findings mapped to OWASP Top 10 + CWE",
      "Reproducible PoC scripts where safe",
      "QSurface provenance chain",
      "Remediation guidance per finding",
      "Free retest within 90 days",
    ],
    whyTLN: [
      "Manual business-logic testing — not just automated scans",
      "We probe authn/authz with the malice of an actual adversary",
      "Multi-tenant SaaS isolation is a specialty",
      "API + GraphQL native (we run our own GraphQL services)",
    ],
    bestFor: ["SaaS products (especially multi-tenant)", "Fintech, health-tech, edtech apps", "Pre-launch + annual recurring tests", "Compliance-driven testing (SOC 2, PCI DSS, HIPAA)"],
  },
  mobile: {
    slug: "mobile",
    title: "Mobile Application Security",
    hero: "iOS + Android. Static + dynamic. Storage to transport to backend.",
    intro: "Mobile apps live in hostile territory — on devices you don't control, against jailbroken environments, with their own threat model. We test the app, the API, and how they trust each other.",
    whatWeTest: [
      "iOS (.ipa) + Android (.apk) static analysis",
      "Local data storage (SQLite, Keychain, Keystore, files)",
      "Transport security (TLS pinning, MITM resistance)",
      "API + backend integration (auth, replay, rate limits)",
      "Inter-process communication, deep links, custom URL schemes",
      "Anti-tampering, anti-debugging, root/jailbreak detection",
      "Third-party SDKs (analytics, ads, crash reporting)",
    ],
    approach: [
      { phase: "01", title: "Static Analysis", desc: "Decompile, reverse, hunt for hardcoded secrets, weak crypto, exposed classes." },
      { phase: "02", title: "Dynamic Analysis", desc: "Run on instrumented devices. Hook runtime. Inspect memory + network." },
      { phase: "03", title: "Backend & API Testing", desc: "Mobile + backend share trust. We test both ends of every call." },
      { phase: "04", title: "Reporting & Remediation", desc: "OWASP MASVS-aligned findings + QSurface chain + remediation guidance." },
    ],
    deliverables: [
      "MASVS-aligned findings",
      "Decompiled artifacts + analysis notes",
      "QSurface provenance chain",
      "Remediation per finding (often code-snippet level)",
      "Free retest within 90 days",
    ],
    whyTLN: [
      "We test the app + the backend together — not separately",
      "Modern mobile threat model (jailbroken devices, hostile networks)",
      "We use real instrumentation (Frida, Objection) — not just static scans",
      "Audit chain proves exactly what was tested on which device build",
    ],
    bestFor: ["Mobile-first SaaS", "Fintech / health / messaging apps", "Apps handling payment or PII", "App Store / Play Store pre-submission audits"],
  },
  cloud: {
    slug: "cloud",
    title: "Cloud Security Audit",
    hero: "AWS. Azure. GCP. The misconfigurations that let attackers walk in.",
    intro: "Cloud breaches almost never come from a clever exploit — they come from a misconfigured IAM policy, an overprivileged service account, or an exposed S3 bucket. We hunt those before attackers find them.",
    whatWeTest: [
      "IAM (roles, policies, service accounts, federation)",
      "Storage exposure (S3, blob, GCS — public + cross-account)",
      "Network architecture (VPC peering, security groups, public subnets)",
      "Secrets management (KMS, Secrets Manager, Key Vault — and what's NOT in them)",
      "Compute (EC2/VMs, Lambda/Functions, K8s workloads)",
      "Data services (RDS, Cosmos, BigQuery — encryption + access)",
      "Cloud-edge services (CloudFront, CDN, API Gateway, ALB/NLB)",
    ],
    approach: [
      { phase: "01", title: "Inventory & Drift", desc: "Read-only scan of your cloud accounts. Diff against your IaC. Find what shouldn't exist." },
      { phase: "02", title: "Identity Attack Paths", desc: "Map the IAM graph. Find privilege-escalation and confused-deputy risks." },
      { phase: "03", title: "Data Exposure & Network", desc: "Public buckets, exposed databases, weak SG rules. The greatest hits." },
      { phase: "04", title: "Reporting & Remediation", desc: "CIS-aligned findings + QSurface chain + IaC remediation snippets." },
    ],
    deliverables: [
      "Findings mapped to CIS Benchmarks + cloud provider best practices",
      "IAM attack-path graphs (visual)",
      "QSurface provenance chain",
      "Terraform / CloudFormation / ARM remediation snippets",
      "Free retest within 90 days",
    ],
    whyTLN: [
      "Multi-cloud experience (AWS, Azure, GCP)",
      "IAM-graph analysis is a specialty (we visualize, not just list)",
      "We hand back IaC code — not just findings",
      "Audit chain works directly with your cloud audit log requirements",
    ],
    bestFor: ["Cloud-native companies", "Multi-cloud or hybrid environments", "Compliance prep (SOC 2, PCI, HIPAA, FedRAMP)", "Post-migration cloud security baseline"],
  },
  network: {
    slug: "network",
    title: "Network & Wireless Security (the literal LAN)",
    hero: "It's right in our name. The LAN you trust — we test it like adversaries do.",
    intro: "Network and wireless infrastructure is where TLN literally started. From the gamer-house T1 line to your corporate WAN — we know how attackers map, pivot, and persist.",
    whatWeTest: [
      "Wired LAN segmentation + VLAN isolation",
      "WiFi (WPA2/WPA3, Enterprise vs PSK, rogue APs, evil twin)",
      "Network access control (NAC) bypass",
      "Switch + router configuration (CDP/LLDP info disclosure, weak SNMP)",
      "VPN concentrators, firewall rule audits",
      "Network device firmware + management interface security",
      "Bluetooth + IoT on the network",
    ],
    approach: [
      { phase: "01", title: "Discovery", desc: "Passive + active mapping of the network estate. Find what's actually there vs what's documented." },
      { phase: "02", title: "Segmentation Validation", desc: "Test the boundaries that are supposed to keep things separate. They often don't." },
      { phase: "03", title: "Wireless Assault", desc: "WPA2/3 attacks, enterprise auth bypass, rogue AP scenarios." },
      { phase: "04", title: "Reporting & Remediation", desc: "Topology diagrams + findings + QSurface chain + segmentation-hardening guidance." },
    ],
    deliverables: [
      "Network topology + attack-path diagrams",
      "Findings per device class with severity",
      "Wireless coverage + risk maps",
      "QSurface provenance chain",
      "Free retest within 90 days",
    ],
    whyTLN: [
      "Network is in our DNA — literally The LAN Network",
      "We test segmentation the way attackers actually exploit it",
      "Wireless engagements include physical site work where needed",
      "Audit chain documents every test on every interface",
    ],
    bestFor: ["Companies with on-prem network estate", "Multi-site / branch-office networks", "Pre-WiFi-rollout audits", "Regulated industries with strict segmentation requirements"],
  },
  social: {
    slug: "social",
    title: "Social Engineering",
    hero: "Phishing. Vishing. Pretext. Train your humans the way you train your firewalls.",
    intro: "Most breaches start with a person, not a bug. Social-engineering engagements measure your real susceptibility — and turn the result into targeted training instead of a cover-your-ass report.",
    whatWeTest: [
      "Phishing (broad + spear-phishing campaigns)",
      "Vishing (phone-based pretexting)",
      "SMS / messaging-app attacks",
      "Physical pretexting (office walk-ins, badge clone scenarios)",
      "USB / dropped-device scenarios",
      "OSINT-based targeting (what attackers can learn before they call)",
    ],
    approach: [
      { phase: "01", title: "Scope & Permission", desc: "Get explicit written sign-off on targets, channels, methods. No surprise lawsuits." },
      { phase: "02", title: "OSINT & Pretext Development", desc: "Build realistic pretexts using public data — show your team how they'd actually be targeted." },
      { phase: "03", title: "Campaign Execution", desc: "Run the campaigns at controlled scale. Capture metrics — clicks, credentials submitted, callbacks." },
      { phase: "04", title: "Reporting & Training", desc: "Anonymized aggregate report (not blame-and-shame) + targeted training recommendations + QSurface chain." },
    ],
    deliverables: [
      "Aggregated metrics (no individual blame)",
      "Pretext detail report (what we tried + why it worked or didn't)",
      "Recommended training topics + frequency",
      "QSurface provenance chain",
      "Optional: re-test campaign after training",
    ],
    whyTLN: [
      "We design pretexts that are realistic — not generic Nigerian-prince stuff",
      "Aggregated reporting protects employee psychology",
      "We pair findings with concrete training topics, not a scolding",
      "Audit chain documents every send, every call, every interaction",
    ],
    bestFor: ["All companies (everyone has humans)", "Industries with high social-engineering risk (finance, healthcare, executives)", "Annual security-awareness program validation", "Post-phishing-incident hardening"],
  },
  redteam: {
    slug: "redteam",
    title: "Red Team Engagement",
    hero: "Adversarial simulation. Goal-based. Stealth-focused. Defense doesn't know we're coming.",
    intro: "Red team is the highest-fidelity test of your entire security program — not just specific assets. We pick a goal (gain domain admin, exfil customer data, compromise CEO inbox) and chain whatever it takes to get there. Your detection + response capabilities are the real subject.",
    whatWeTest: [
      "End-to-end attack chains (initial access → persistence → exfil)",
      "Detection + response capability (SOC, SIEM, EDR, IR playbooks)",
      "Cross-domain pivots (network → identity → cloud → SaaS)",
      "Long-dwell scenarios (weeks of low-and-slow access)",
      "Custom tooling + living-off-the-land techniques",
      "Real adversary TTP emulation (FIN, APT-style threat actors)",
    ],
    approach: [
      { phase: "01", title: "Threat Modeling & Goal", desc: "Pick the adversary. Pick the goal. Get sign-off on rules of engagement." },
      { phase: "02", title: "Initial Access", desc: "Phishing, supply chain, exposed service — whatever realistic path fits the threat model." },
      { phase: "03", title: "Action on Objectives", desc: "Pivot, escalate, persist, exfil. Quietly. Test detection + response in real time." },
      { phase: "04", title: "Reporting & Purple-Team Debrief", desc: "Full attack narrative + detection-gap analysis + QSurface chain + collaborative SOC training session." },
    ],
    deliverables: [
      "Full kill-chain attack narrative",
      "Detection gap analysis (per technique, per phase)",
      "QSurface provenance chain (full timeline of every action)",
      "Optional purple-team training session (highly recommended)",
      "Tooling artifacts (where appropriate to share)",
    ],
    whyTLN: [
      "We emulate real threat actors, not generic 'pen test' patterns",
      "Long-dwell engagements available (weeks not hours)",
      "Audit chain gives your SOC a perfect detection-engineering training set",
      "Optional purple-team debrief turns the engagement into a teaching moment",
    ],
    bestFor: ["Mature security programs validating SOC + IR", "Post-breach hardening after a real incident", "Companies in heavily-targeted industries", "Annual board-level security validation"],
  },
  methodology: {
    slug: "methodology",
    title: "Our Methodology",
    hero: "Six phases. AI-augmented in the heavy lift. Human-led in the high-judgment.",
    intro: "Every TLN engagement runs the same disciplined arc — adapted to the engagement type. We document each phase in the QSurface provenance chain so your auditors get cryptographic proof of exactly what happened, when, on which hardware.",
    whatWeTest: [
      "Whatever your scope says — and nothing outside it",
      "Documented in the SOW before any testing begins",
      "Every action signed in the QSurface chain in real time",
    ],
    approach: [
      { phase: "01", title: "Scope & Threat Model", desc: "Map your attack surface to your business risk. Not every asset deserves the same depth." },
      { phase: "02", title: "Reconnaissance", desc: "Passive + active. We learn your tech stack the way an adversary would — without alerting you." },
      { phase: "03", title: "Exploitation", desc: "Manual testing led by humans, augmented by our AI compute fabric for coverage scaling." },
      { phase: "04", title: "Post-Exploitation", desc: "What does a foothold actually buy an attacker in YOUR environment? We measure blast radius." },
      { phase: "05", title: "Reporting & Audit Chain", desc: "Executive + technical report. Plus the cryptographically-signed provenance chain." },
      { phase: "06", title: "Remediation Support", desc: "We don't drop a PDF and disappear. Retests included. Your team gets human help." },
    ],
    deliverables: [
      "Executive report (board-language risk summary)",
      "Technical findings (reproducible, prioritized)",
      "QSurface provenance chain (industry-first cryptographic engagement log)",
      "Remediation guidance",
      "Free retest within 90 days",
    ],
    whyTLN: [
      "Same disciplined arc on every engagement — predictable, documented",
      "AI augmentation where it scales coverage; humans where judgment matters",
      "QSurface chain = first-of-its-kind audit primitive",
      "Post-engagement support is included, not upsold",
    ],
    bestFor: ["Anyone evaluating us — read this before requesting a quote"],
  },
};
